<!-- Flickr AJAX call -->
<script type="text/javascript">
//Flickr API: Find photos based on destination and tag name as tags"
(function() {
  var destTag = "<?= $this->idea->destination ?>";
  var tagTag = "<?= $this->tags[0]->tag ?>";
  
  var flickerAPI = "http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?";
  $.getJSON(flickerAPI, {
    tags: "Travel," + destTag + "," + tagTag,
    tagmode: "all",
    format: "json"
  })
  .done(function( data ) {
	if(data.items.length==0){
		$( "#images" ).append( "<p>No images available.</p>" );
	}
	else{
		$.each( data.items, function( i, item ) {
			//Get 5 photos per page
			$( "<img>" ).attr( "src", item.media.m ).appendTo( "#images" );
				if ( i === 4 ) {
					return false;
				}
		});
	}
  });
})();
</script>
<!-- End of Flickr AJAX call -->

<!-- Travel Idea Comments List -->
<script type="text/javascript">
var numComments;
$(document).ready(function(){
    //Count and display the number of comments
    numComments = $('.msgln').length;
    document.getElementById("numComments").textContent = numComments;
});
var logID = "<?= $this->idea->id; ?>";
function loadLog(){
	if(numComments > 0) { 
		var oldscrollHeight = $("#chatbox").attr("scrollHeight") - 20; //Scroll height before the request
	    $.ajax({
	        url: "/idea_" + logID + "_comment.html",
	        cache: false,
	        success: function(html){        
	            $("#chatbox").html(html); //Insert chat log into the #chatbox div
	            //Auto-scroll           
	            var newscrollHeight = $("#chatbox").attr("scrollHeight") - 20; //Scroll height after the request
	            if(newscrollHeight > oldscrollHeight){
	                $("#chatbox").animate({ scrollTop: newscrollHeight }, 'normal'); //Autoscroll to bottom of div
	            }               
	        },
	    });
	}
}
setInterval (loadLog, 2500);
</script>
<!-- End of Travel Idea Comments List -->

<div id="content">
<!-- Detailed Travel Idea -->
<div id="detail">
<h2><?= $this->idea->title ?></h2>
	Destination: <?= $this->idea->destination ?><br/>
	Travel Date:
	<? 
		$startTimeStamp = strtotime($this->idea->startDate);
		echo date('d/m/Y', $startTimeStamp);
	?> to
	<?
		$endTimeStamp = strtotime($this->idea->endDate);
		echo date('d/m/Y', $endTimeStamp);
	?>
	<br/>
	<? if (count($this->tags)>0){ ?>
		<? echo "Tags:" ?>
	<? } ?>
	<? foreach($this->tags as $tag) { ?>
	   <?= $tag->tag ?>;
	<? } ?>
	<br/>
	Author: <?= $this->idea->author->memberLogin ?><br/>
	<br/>
</div>
<!-- End of Detailed Travel Idea -->
	
<!-- Expedia Hotel Recommendation -->
<div id="expedia">
<?php
//Variables in hotel search
$inputCity = $this->idea->destination;
//Input formatting: Convert to lower case and space
$city = strtolower( str_replace(' ', '', $inputCity));

//Expedia API: Find hotel recommendation based on the destination by formulating the URL
//Old URL from Expedia which fails
//$url  ='http://api.ean.com/ean-services/rs/hotel/v3/list?minorRev=99';
//New URL suggested by Expedia
$url  ='http://dev.api.ean.com/ean-services/rs/hotel/v3/list?minorRev=99';
$url .= '&apiKey=6dsgvvy8ccnfmpfk6t6uvvk3';
$url .= '&cid=55505';
$url .= '&locale=en_US';
$url .= '&city=' . $city;
$url .= '&searchRadius=50';
$url .= '&supplierCacheTolerance=MED_ENHANCED';
$url .= '&arrivalDate='. date('m/d/Y', $startTimeStamp);
$url .= '&departureDate'. date('m/d/Y', $endTimeStamp);
$url .= '&room1=2';

$header[] = "Accept: application/json";
$header[] = "Accept-Encoding: gzip";
$ch = curl_init();
curl_setopt( $ch, CURLOPT_HTTPHEADER, $header );
curl_setopt($ch,CURLOPT_ENCODING , "gzip");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
curl_setopt( $ch, CURLOPT_URL, $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$response = json_decode(curl_exec($ch), true);

//Check if "HotelList" array is empty
if (array_key_exists('HotelList', $response['HotelListResponse'])) {
	// Get the returned array size
	$rep_arr_size = $response['HotelListResponse']['HotelList']['@size'];
	// Desired display result
	$number_of_results = 10;
?>

<h2>Expedia Hotel Recommendation</h2>
<table id="expediaTable" class="tablesorter">
	<thead>
		<tr>
			<th class="tabletab">Hotel Name</th>
			<th class="tabletab">Address</th>
			<th class="tabletab">Rating</th>
			<th class="tabletab">Location</th>
		</tr>
	</thead>
		    <?php
			for ($x=0; $x<$number_of_results; $x++){
		    ?>
			<tr>
			   <td class="value"><?=$response['HotelListResponse']['HotelList']['HotelSummary'][$x]['name']?></td>
			   <td class="value"><?=$response['HotelListResponse']['HotelList']['HotelSummary'][$x]['address1']?></td>
			   <td class="value"><?=$response['HotelListResponse']['HotelList']['HotelSummary'][$x]['hotelRating']?></td>
			   <td class="value"><?=$response['HotelListResponse']['HotelList']['HotelSummary'][$x]['locationDescription']?></td>
			</tr>
			<? } ?>
		 <? } 
else { ?>
	<tr>
		<td colspan="4"><h2>Expedia Hotel Recommendation</h2></td>
	</tr>
	<tr><td colspan="4" class="value">Results Unavailable.</td></tr>
	<tr><td colspan="4" class="value">&nbsp;</td></tr>
<? } ?>
</table>
<br/>
</div>
<!-- End of Expedia Hotel Recommendation -->

<!-- Travel Idea Comments List Display -->
<div id="wrapper">
	<h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total <text id="numComments"></text> comment(s)</h2>
    <div id="chatbox">
	<?php
    	//Get comment list ID
		$id = $this->idea->id;
		
		if(file_exists("idea_".$id."_comment.html") && filesize("idea_".$id."_comment.html") > 0){
			$handle = fopen("idea_".$id."_comment.html", "r");
			$contents = fread($handle, filesize("idea_".$id."_comment.html"));
			fclose($handle);
			echo $contents;			
		}
	?>
	</div>
	<div id="form">
	    <form action="" name="message" method="post">
	        <p>Your comments:</p>
	        <input type="text" name="usermsg" id="usermsg" size="50" maxlength="255" value="<?=$this->escape($this->usermsg);?>" />
	        <input type="submit" name="submitmsg" id="submitmsg" value="Send"/>
	    </form>
    </div>
</div>
<!-- End of Travel Idea Comments List Display -->

<!-- Flickr Image Display -->
<br/><br/>
<div id="images"></div>
<!-- End of Flickr Image Display -->
<br/>
</div>