<script type="text/javascript">
$(document).ready(function() 
	{ 
		$("#ideasTable").tablesorter();
	}
);
</script>

<section>
<article>
<?php 
	$count = count($this->ideas);
	if ($count > 0){
?>
<table id="ideasTable" class="tablesorter">
	<thead>
		<tr>
			<th class="titletab">Title</th>
			<th class="tabletab">Destination</th>
			<th class="tabletab">Travel Date</th>
			<th class="tabletab">Author</th>
		</tr>
	</thead>
	<? foreach($this->ideas as $idea) { ?>
	<tr>
		<td class="value">
		    <a href="/ideas/detail/id/<?= $idea->id ?>">
<?php
	if (strlen($idea->title) > 100) {
        echo substr($idea->title,0,100)."...";
    } else {
        echo $idea->title;
    }
?>
		    </a>
		</td>
		<td class="value"><?= $idea->destination ?></td>
		<td class="value">
		<?
			$startTimeStamp = strtotime($idea->startDate);
		   	echo date('d/m/Y', $startTimeStamp);
		?>
		</td>
		<td class="value"><?= $idea->author->memberLogin ?></td>
	</tr>
	<? } ?>
</table>
<br/>
<? } ?>
</article>
</section>