<?php include "header.phtml"; ?>


<?php
	$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
	if ($flashMessenger->setNamespace('success')->hasMessages()):
	foreach ($flashMessenger->getMessages() as $msg):
		echo "<p><mark>" . $msg . "</mark></p>";

	endforeach;
	endif;
	if ($flashMessenger->setNamespace('error')->hasMessages()):
	foreach ($flashMessenger->getMessages() as $msg):
		echo "<p><mark>" . $msg . "</mark></p>";
	endforeach;
	endif;
?>

<section id="search_result">
	<?=$this->layout()->content; ?>
</section>

<?php include "footer.phtml"; ?>